### ISSUE TITLE
error:  no sync db 'aurto' configured?

### ISSUE THREAD

**Issue by wertercatt** [alexheretic/aurto#30] opened 2019-11-26 02:53 UTC
I'm a new user who just installed Arch. I followed the instructions in the aurto README.md, but I run into this error when trying to run "aurto add aurto"

**Comment by alexheretic** [comment] 2019-11-26 07:31
Thanks, I'll try to reproduce this when I get a moment.

**Comment by wertercatt** [comment] 2019-11-28 19:38
Figured out a manual fix for this that should at least be documented. (Note, $your-home refers to your directory in /home/)
Add this to /etc/pacman.conf (requires root or sudo)
`[aurto]
SigLevel = Optional TrustAll
Server = file:///home/$your-home/aurtopkgs`
run these commands
`mkdir /home/$your-home/aurtopkgs
repo-add /home/$your-home/aurtopkgs/aurto.db.tar`
For more info check https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Custom_local_repository

**Comment by alexheretic** [comment] 2019-11-28 19:46
The location of the aurto repo is `/var/cache/pacman/aurto/aurto.db.tar` and that's relied upon by the scripts, so these steps won't work fully.

The install script creates this repo, can you check `/usr/lib/aurto/user` this should match your user. I'm just wondering if your install was with a different user this may be the cause of your issues.

I actually want to get around to moving user stuff to the home dir, but that requires some time...

**Comment by wertercatt** [comment] 2019-11-28 19:54
`/usr/lib/aurto/user` matches my username, but the install script did not create anything in `/var/cache/pacman/aurto`. That directory is empty.

**Comment by alexheretic** [comment] 2019-11-28 20:12
What happens when you run `repo-add /var/cache/pacman/aurto/aurto.db.tar` as your user?

Uninstalling then re-installing will run the script again. 

Otherwise the install script is here: https://aur.archlinux.org/cgit/aur.git/tree/aurto.install?h=aurto you could try executing the steps manually (as root) and see what fails. Maybe a `2>/dev/null` is hiding an error during install that I haven't encountered.

**Comment by wertercatt** [comment] 2019-11-28 20:28
The command created aurto.db.tar as expected. I tried to manually run aurto.install and discovered that it had apparently been set as non-executable when I makepkg installed aurto. That's probably the cause of my issues.

**Comment by AladW** [comment] 2020-02-23 11:18
I have some questions with an install script like that. AUR packages really shouldn't do all these automation steps in an install script, *especially* not modify system files. 

* Making backups of `/etc/pacman.conf` doesn't really help with that since between installation and removal or `aurto`, any arbitrary kind of changes could have been made to that file, and 1 mistake in the install logic and it goes up in smoke. 
* The `$user` stuff will also break if pacman is run without `sudo`, e.g. from a root shell or with `su`.
* Use `systemd.preset` if you explicitely want to enable services for users. The actual starting can be left to the user.

**Comment by alexheretic** [comment] 2020-02-23 13:24
These points are a different issue really, this issue is still open because I don't fully understand what when wrong here.

> Making backups of /etc/pacman.conf doesn't really help with that since between installation and removal or aurto, any arbitrary kind of changes could have been made to that file, and 1 mistake in the install logic and it goes up in smoke.

I agree I'd rather not have to edit pacman.conf at install & remove, at the same time the objective was to have as close to a zero config experience as possible. There's nothing interesting to setup here for aurto, if you want to do more custom stuff using aurutils directly makes more sense.

I do think the current edits are pretty precise though, appending 2 lines & removing only exactly those two lines on removal. If they've been edited since they won't be removed which seems right. The backup to `/etc/pacman.conf.aurto-backup` is just an extra safety & not really necessary.

Another options is having a `aurto init` command that sets this up, maybe in an interactive way. But it still comes down to a script setting stuff up in pacman.conf, so I'm not sure if it's too much better.

> The $user stuff will also break if pacman is run without sudo, e.g. from a root shell or with su.

This user is only used by the update script which _does_ call pacman with sudo. Why would it matter if pacman was called elsewhere without sudo?

> Use systemd.preset if you explicitely want to enable services for users. The actual starting can be left to the user.

This is another zero config thing. But could tie into the `aurto init` idea with the services initially disabled. Again it's a _do it at install_ vs _do it when you run aurto init_ issue, you'll need root currently so I stepped more towards the former.

I would like to have aurto run totally in as a user and in the home dir using systemd --user timers. The idea is nice, but last time I looked into it though there is too much dependency on running certain tasks as root.

**Comment by AladW** [comment] 2020-02-24 01:57
> I do think the current edits are pretty precise though, appending 2 lines & removing only exactly those two lines on removal. 

You're missing the point. It's about an AUR package taking arbitrary modifications to a system file. If you had an "init" or whatever, at least the modification has to be taken explicitely by the user.

> This user is only used by the update script which does call pacman with sudo.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aurto#n18

That's called by pacman whenever aurto is installed. That can be done with makepkg -i (which runs sudo) or pacman -U with root, by any means to achieve root which does not necessarily set SUDO_USER.

**Comment by alexheretic** [comment] 2020-02-24 08:01
> You're missing the point. It's about an AUR package taking arbitrary modifications to a system file. If you had an "init" or whatever, at least the modification has to be taken explicitely by the user.

Ok I think losing the install script and using an `aurto init` step should be an improvement then.

> That's called by pacman whenever aurto is installed. That can be done with makepkg -i (which runs sudo) or pacman -U/-S with root, by any means to achieve root which does not necessarily set SUDO_USER.

I see what you mean now. Though unfortunately it doesn't explain _this_ issue as the user had been set correctly. But in any case moving to an init call will solve this too.

**Comment by AlexFolland** [comment] 2020-09-12 07:53
I'm getting this error right now immediately after having installed `aurto` from the AUR with `yay`.  What do I do?

```
[alex@alex-pc ~]$ yay -Ss aurto
aur/aurto 0.9.10-2 (+10 1.01) (Installed)
    An AUR tool for managing an auto-updating local 'aurto' package repository using aurutils.
aur/python3-aur 2018.8-4 (+210 1.64) 
    AUR-related modules and helper utilities (aurploader, aurquery, aurtomatic).
[alex@alex-pc ~]$ aurto add aurto
aurto: Checking maintainer trust... disabled
error: no sync db 'aurto' configured
[alex@alex-pc ~]$
```

**Comment by alexheretic** [comment] 2020-09-12 12:21
I'm not 100% why that would happen using `yay`. Maybe the install script didn't run or was setup as an incorrect user?

I'd try uninstalling it and retry using the makepkg method https://github.com/alexheretic/aurto#install.

**Comment by daniel-light** [comment] 2020-10-03 23:46
after installing by aurget I was getting a lot of `ERROR: sync: /var/cache/pacman/aurto/aurto.db: permission denied` type stuff (`/usr/lib/aurto/user` was me, if that's relevant), but after reading this issue and installing by makepkg it seems to be working -  it might be worth calling this out as a troubleshooting solution for people migrating from other AUR helpers.

**Comment by alexheretic** [comment] 2020-10-09 17:25
`aurto init` replaces what the install script did previously and should fix this issue (or make the error clearer). I'll close this and we can deal with `aurto init` errors as they arise.

**Closed by alexheretic** 2020-10-09 17:25 UTC
